// Daily quotes about the greatness of fasting and helping others from the Quran
const dailyQuotes = [
  "Indeed, Allah is with those who fear Him and those who are doers of good. - Surah An-Nahl (16:128) | إن الله مع الذين اتقوا والذين هم محسنون. - سورة النحل",
  "And when My servants ask you concerning Me, indeed I am near. I respond to the invocation of the supplicant when he calls upon Me. - Surah Al-Baqarah (2:186) | وإذا سألك عبادي عني فإني قريب. أجيب دعوة الداع إذا دعان. - سورة البقرة",
  "So remember Me; I will remember you. And be grateful to Me and do not deny Me.- Surah Al-Baqarah (2:152) | فاذكروني أذكركم واشكروا لي ولا تكفرون. - سورة البقرة",
  "And whatever good you put forward for yourselves - you will find it with Allah. - Surah Al-Baqarah (2:110) | وما تقدموا لأنفسكم من خير تجدوه عند الله. - سورة البقرة",
  "For indeed, with hardship [will be] ease. - Surah Ash-Sharh (94:6) | فإن مع العسر يسرا. - سورة الشرح",
  "And the servants of the Most Merciful are those who walk upon the earth easily, and when the ignorant address them [harshly], they say [words of] peace. - Surah Al-Furqan (25:63) | وعباد الرحمن الذين يمشون على الأرض هونا وإذا خاطبهم الجاهلون قالوا سلاما. - سورة الفرقان",
  "But give glad tidings to those who patiently persevere. - Surah Al-Baqarah (2:155) | وبشر الصابرين. - سورة البقرة",
  "Indeed, Allah does not wrong the people at all, but it is the people who are wronging themselves.- Surah Yunus (10:44) | إن الله لا يظلم الناس شيئا ولكن الناس أنفسهم يظلمون. - سورة يونس",
  "And hasten to forgiveness from your Lord and a garden as wide as the heavens and earth, prepared for the righteous. - Surah Ali 'Imran (3:133) | وسارعوا إلى مغفرة من ربكم وجنة عرضها السماوات والأرض أعدت للمتقين. - سورة آل عمران",
  "And spend in the way of Allah and do not throw [yourselves] with your [own] hands into destruction [by refraining]. - Surah Al-Baqarah (2:195) | وأنفقوا في سبيل الله ولا تلقوا بأيديكم إلى التهلكة. - سورة البقرة",
  "And let not those of virtue among you and wealth swear not to give [aid] to their relatives and the needy and the migrants for the cause of Allah, and let them pardon and overlook. - Surah An-Nur (24:22) | ولا يأتل أولو الفضل منكم والسعة أن يؤتوا أولي القربى والمساكين والمهاجرين في سبيل الله وليعفوا وليصفحوا. - سورة النور",
  "O mankind, indeed We have created you from male and female and made you peoples and tribes that you may know one another.- Surah Al-Hujurat (49:13) | يا أيها الناس إنا خلقناكم من ذكر وأنثى وجعلناكم شعوبا وقبائل لتعارفوا. - سورة الحجرات",
  "Indeed, the patient will be given their reward without account. - Surah Az-Zumar (39:10) | إنما يوفى الصابرون أجرهم بغير حساب. - سورة الزمر",
  "And what is the life of this world except the enjoyment of delusion. - Surah Al-Imran (3:185) | وما الحياة الدنيا إلا متاع الغرور. - سورة آل عمران",
  "Say, 'Indeed, my prayer, my rites of sacrifice, my living and my dying are for Allah, Lord of the worlds.' - Surah Al-An'am (6:162) | قل إن صلاتي ونسكي ومحياي ومماتي لله رب العالمين. - سورة الأنعام",
  "And He is with you wherever you are.- Surah Al-Hadid (57:4) | وهو معكم أينما كنتم. - سورة الحديد",
  "So verily, with the hardship, there is relief. - Surah Ash-Sharh (94:5) | فإن مع العسر يسرا. - سورة الشرح",
  "And those who strive for Us - We will surely guide them to Our ways.- Surah Al-Ankabut (29:69) | والذين جاهدوا فينا لنهدينهم سبلنا. - سورة العنكبوت",
  "Indeed, this Quran guides to that which is most suitable.- Surah Al-Isra (17:9) | إن هذا القرآن يهدي للتي هي أقوم. - سورة الإسراء",
  "And do not walk upon the earth exultantly. Indeed, you will never tear the earth apart, and you will never reach the mountains in height. - Surah Al-Isra (17:37) | ولا تمش في الأرض مرحا. إنك لن تخرق الأرض ولن تبلغ الجبال طولا. - سورة الإسراء",
  "Indeed, my Lord is on a path [that is] straight.- Surah Hud (11:56) | إن ربي على صراط مستقيم. - سورة هود",
  "So be patient. Indeed, the promise of Allah is truth.- Surah Ar-Rum (30:60) | فاصبر إن وعد الله حق. - سورة الروم",
  "And Allah invites to the Home of Peace and guides whom He wills to a straight path.- Surah Yunus (10:25) | والله يدعو إلى دار السلام ويهدي من يشاء إلى صراط مستقيم. - سورة يونس",
  "For those who have done good is the best [reward] and extra. - Surah Yunus (10:26) | للذين أحسنوا الحسنى وزيادة. - سورة يونس",
  "And when you have decided, then rely upon Allah. Indeed, Allah loves those who rely [upon Him].- Surah Ali 'Imran (3:159) | وإذا عزمت فتوكل على الله. إن الله يحب المتوكلين. - سورة آل عمران",
  "Indeed, the righteous will be among gardens and rivers.- Surah Al-Qamar (54:54) | إن المتقين في جنات ونهر. - سورة القمر",
  "Say, 'He is Allah, [who is] One.' - Surah Al-Ikhlas (112:1) | قل هو الله أحد. - سورة الإخلاص",
  "Indeed, Allah commands you to render trusts to whom they are due and when you judge between people to judge with justice.  - Surah An-Nisa (4:58) | إن الله يأمركم أن تؤدوا الأمانات إلى أهلها وإذا حكمتم بين الناس أن تحكموا بالعدل. - سورة النساء",
  "And do good; indeed, Allah loves the doers of good.-  Surah Al-Baqarah (2:195) | وأحسنوا إن الله يحب المحسنين. - سورة البقرة",
  "And be not like those who forgot Allah, so He made them forget themselves.- Surah Al-Hashr (59:19) | ولا تكونوا كالذين نسوا الله فأنساهم أنفسهم. - سورة الحشر",
];

export default dailyQuotes;
